name: Elevator
version: 1.0
main: com.comonier.elevator.Elevator
api-version: '1.21'
author: comonier
description: Plugin de elevadores simples por blocos.

commands:
  elevator:
    description: Comando principal do plugin Elevator.
    usage: /elevator
    aliases: [elev, elevador]

permissions:
  elevator.use:
    description: Permite usar os elevadores (caso ativado na config).
    default: true
  elevator.admin:
    description: Permite recarregar as configurações do plugin.
    default: op
